apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-ds-service.yml
  - backend-ds-service.yml
  - db-ds-service.yaml
  - alb-ingress.yml
  - secrets-configmap.yml
